repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: end-of-file-fixer
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: fix-byte-order-marker
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
