/**
 * GAMS Engine
 * With GAMS Engine you can register and solve GAMS models. It has a namespace management system, so you can restrict your users to certain models.
 *
 * The version of the OpenAPI document: latest
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIModel_version.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIModel_version::OAIModel_version(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIModel_version::OAIModel_version() {
    this->initializeModel();
}

OAIModel_version::~OAIModel_version() {}

void OAIModel_version::initializeModel() {

    m_gams_version_isSet = false;
    m_gams_version_isValid = false;

    m_version_isSet = false;
    m_version_isValid = false;
}

void OAIModel_version::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIModel_version::fromJsonObject(QJsonObject json) {

    m_gams_version_isValid = ::OpenAPI::fromJsonValue(gams_version, json[QString("gams_version")]);
    m_gams_version_isSet = !json[QString("gams_version")].isNull() && m_gams_version_isValid;

    m_version_isValid = ::OpenAPI::fromJsonValue(version, json[QString("version")]);
    m_version_isSet = !json[QString("version")].isNull() && m_version_isValid;
}

QString OAIModel_version::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIModel_version::asJsonObject() const {
    QJsonObject obj;
    if (m_gams_version_isSet) {
        obj.insert(QString("gams_version"), ::OpenAPI::toJsonValue(gams_version));
    }
    if (m_version_isSet) {
        obj.insert(QString("version"), ::OpenAPI::toJsonValue(version));
    }
    return obj;
}

QString OAIModel_version::getGamsVersion() const {
    return gams_version;
}
void OAIModel_version::setGamsVersion(const QString &gams_version) {
    this->gams_version = gams_version;
    this->m_gams_version_isSet = true;
}

bool OAIModel_version::is_gams_version_Set() const{
    return m_gams_version_isSet;
}

bool OAIModel_version::is_gams_version_Valid() const{
    return m_gams_version_isValid;
}

QString OAIModel_version::getVersion() const {
    return version;
}
void OAIModel_version::setVersion(const QString &version) {
    this->version = version;
    this->m_version_isSet = true;
}

bool OAIModel_version::is_version_Set() const{
    return m_version_isSet;
}

bool OAIModel_version::is_version_Valid() const{
    return m_version_isValid;
}

bool OAIModel_version::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_gams_version_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_version_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIModel_version::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
