/**
 * GAMS Engine
 * With GAMS Engine you can register and solve GAMS models. It has a namespace management system, so you can restrict your users to certain models.
 *
 * The version of the OpenAPI document: latest
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIModel_job_labels.h
 *
 * 
 */

#ifndef OAIModel_job_labels_H
#define OAIModel_job_labels_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIModel_job_labels : public OAIObject {
public:
    OAIModel_job_labels();
    OAIModel_job_labels(QString json);
    ~OAIModel_job_labels() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    double getCpuRequest() const;
    void setCpuRequest(const double &cpu_request);
    bool is_cpu_request_Set() const;
    bool is_cpu_request_Valid() const;

    qint32 getMemoryRequest() const;
    void setMemoryRequest(const qint32 &memory_request);
    bool is_memory_request_Set() const;
    bool is_memory_request_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    double cpu_request;
    bool m_cpu_request_isSet;
    bool m_cpu_request_isValid;

    qint32 memory_request;
    bool m_memory_request_isSet;
    bool m_memory_request_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIModel_job_labels)

#endif // OAIModel_job_labels_H
