/**
 * GAMS Engine
 * GAMS Engine let's you register, solve and get results of GAMS Models. It has namespace management system so you can restrict your users to certain set of models.
 *
 * The version of the OpenAPI document: latest
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIStream_entry.h
 *
 * 
 */

#ifndef OAIStream_entry_H
#define OAIStream_entry_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIStream_entry : public OAIObject {
public:
    OAIStream_entry();
    OAIStream_entry(QString json);
    ~OAIStream_entry() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getEntryValue() const;
    void setEntryValue(const QString &entry_value);
    bool is_entry_value_Set() const;
    bool is_entry_value_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString entry_value;
    bool m_entry_value_isSet;
    bool m_entry_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIStream_entry)

#endif // OAIStream_entry_H
