/**
 * GAMS Engine
 * GAMS Engine let's you register, solve and get results of GAMS Models. It has namespace management system so you can restrict your users to certain set of models.
 *
 * The version of the OpenAPI document: dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIStatus_code_meaning.h
 *
 * 
 */

#ifndef OAIStatus_code_meaning_H
#define OAIStatus_code_meaning_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIStatus_code_meaning : public OAIObject {
public:
    OAIStatus_code_meaning();
    OAIStatus_code_meaning(QString json);
    ~OAIStatus_code_meaning() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getStatusCode() const;
    void setStatusCode(const qint32 &status_code);

    QString getDescription() const;
    void setDescription(const QString &description);

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 status_code;
    bool m_status_code_isSet;
    bool m_status_code_isValid;

    QString description;
    bool m_description_isSet;
    bool m_description_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIStatus_code_meaning)

#endif // OAIStatus_code_meaning_H
