fetch-prerequisites:
  stage: fetch-prerequisites
  when: always
  tags: [linux]
  needs: []
  image:
    name: $GAMS_CONTAINER_REGISTRY/machines/leg/builder-full:latest
    entrypoint: [ "" ]
  script:
    # fetch helper scripts
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@$GITLAB_CISCRIPTS_URL scripts-repo
    - cp -R scripts-repo/ci .
    # fetch GAMS for Windows
    - python3 ci/fetch_gams.py fetch_wei $PF_CUSTOM_BRANCH $SSH_KEY_PORTING force
    - python3 ci/fetch_gams.py fetch_wei $PF_CUSTOM_BRANCH $SSH_KEY_PORTING buildInfo
  artifacts:
    name: fetch-prerequisites
    expire_in: 15 minutes
    paths: [windows_x64_64.exe,buildInfo.txt,ci/*]

install-gams-leg:
  stage: install-gams
  tags: [linux]
  needs: [fetch-prerequisites]
  image:
    name: $GAMS_CONTAINER_REGISTRY/machines/leg/builder-full:latest
    entrypoint: [""]
  script:
    - GAMS_LICENSE=$GAMS_LICENSE python3 ci/fetch_gams.py fetch_and_install_leg $PF_CUSTOM_BRANCH $SSH_KEY_PORTING

install-gams-deg:
  stage: install-gams
  tags: [macos]
  needs: [fetch-prerequisites]
  script:
    - GAMS_LICENSE=$GAMS_LICENSE python3 ci/fetch_gams.py fetch_and_install_deg $PF_CUSTOM_BRANCH $SSH_KEY_PORTING

install-gams-dac:
  stage: install-gams
  tags: [macos-arm64]
  dependencies: [fetch-prerequisites]
  script:
    - GAMS_LICENSE=$GAMS_LICENSE python3 ci/fetch_gams.py fetch_and_install_dac $PF_CUSTOM_BRANCH $SSH_KEY_PORTING

install-gams-wei:
  stage: install-gams
  tags: [windows]
  needs: [fetch-prerequisites]
  image:
    name: $GAMS_CONTAINER_REGISTRY/machines/wei/builder-full:latest
    entrypoint: [""]   # prevent startup.sh
  script:
    - python ci/fetch_gams.py install $PF_CUSTOM_BRANCH $GAMS_LICENSE $SSH_KEY_PORTING
    - python ci/fetch_gams.py version $PF_CUSTOM_BRANCH
  artifacts:
    name: wei-gmsdirpath
    expire_in: 15 minutes
    paths: [mygmsdir.tmp]
