# =============================================================================
# 1. Cleanup outdated artifacts for Merge Requests
#    - Ensure in https://git.gams.com/devel/studio/-/settings/ci_cd
#      to turn off Artifacts: Keep artifacts from most recent successful jobs
# =============================================================================
clean_previous_mr_artifacts:
  stage: .pre
  tags: [linux]
  image: alpine:latest
  dependencies: []
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Check old pipelines for this MR ($CI_MERGE_REQUEST_IID)..."
    - PIPELINES=$(curl --fail --header "PRIVATE-TOKEN: $ARTIFACT_CLEANUP_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/pipelines" | grep -o '"id":[0-9]*' | grep -o '[0-9]*' || true)
    - |
      if [ -z "$PIPELINES" ]; then
        echo "No old pipelines found."
      else
        for PREV_PID in $PIPELINES; do
          if [ "$PREV_PID" != "$CI_PIPELINE_ID" ]; then
            echo "Deleting artifacts from old pipeline #$PREV_PID..."
            curl --request DELETE --header "PRIVATE-TOKEN: $ARTIFACT_CLEANUP_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$PREV_PID/artifacts"
          fi
        done
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Only in MR-Context

# =============================================================================
# 2. Process pre-commit
# =============================================================================
quality-gate:
  stage: quality
  tags: [linux]
  image:
    name: $GAMS_CONTAINER_REGISTRY/qt-machines/leg/analyzer-${QT_IMAGE_VERSION}:latest
    entrypoint: [""]   # prevent startup.sh
  script:
    - git config --global http.version HTTP/1.1
    - SKIP=end-of-file-fixer pre-commit run -a
