# =============================================================================
#  Merge Request: Stoping the environment deletes the artifacts
# =============================================================================

stop_all_platforms:
  stage: cleanup
  allow_failure: true
  tags: [linux]
  dependencies: [] # Do not download the artifact here
  variables:
    GIT_STRATEGY: none
  environment:
    name: mr-cleanup/$CI_COMMIT_REF_SLUG
    action: stop
  script:
    - echo "MR closed or merged. Stop environment triggers purge of artifacts"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual


# =============================================================================
#  TAG: Create a dummy job to break the "keep latest artifact" locking
# =============================================================================
unlock_tag_artifact:
  stage: cleanup
  dependencies: [] # Do not download the artifact here
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Overwriting the latest job status for this tag without creating artifacts."
  rules:
    - if: '$CI_COMMIT_TAG'
