# =============================================================================
#  Stoping the environment deletes the artifacts
# =============================================================================

stop_all_platforms:
  stage: cleanup
  allow_failure: true
  tags: [linux]
  dependencies: []  # avoids downloading any artifacts into this job
  variables:
    GIT_STRATEGY: none
  environment:
    name: mr-cleanup/$CI_COMMIT_REF_SLUG
    action: stop
  script:
    - echo "MR closed or merged. Stop environment triggers purge of artifacts"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
